---

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 86400
  ignore_errors: true
  become: true

- name: Install apt dependencies.
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ app_fightfor_graphql.dependencies_apt }}"
  become: true

- name: Create service group.
  group:
    state: present
    name: "{{ app_fightfor_graphql.group }}"
  become: true

- name: Create service user.
  user:
    state: present
    name: "{{ app_fightfor_graphql.user }}"
    createhome: yes
    group: "{{ app_fightfor_graphql.group }}"
    shell: "/bin/false"
  become: true

- name: Create application directories.
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ app_fightfor_graphql.user }}"
    mode: 0755
  with_items:
    - "{{ app_fightfor_graphql.share_dir }}"
    - "{{ app_fightfor_graphql.config_dir }}"
    - "{{ app_fightfor_graphql.run_dir }}"
    - "{{ app_fightfor_graphql.log_dir }}"
  become: true

- name: Install system-level Python dependencies
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ app_fightfor_graphql.dependencies_pip_system }}"
  become: true

- name: Install deployment-level pip dependencies not included in a `requirements.txt` within the virtual environment
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ app_fightfor_graphql.virtual_env_dir }}"
    virtualenv_python: python3.5
  with_items: "{{ app_fightfor_graphql.dependencies_pip_virtualenv }}"
  become: true
  become_user: "{{ app_fightfor_graphql.user }}"

- name: Create .ssh directory (Production)
  file:
    state: directory
    path: "/home/{{ app_fightfor_graphql.user }}/.ssh"
    owner: "{{ app_fightfor_graphql.user }}"
    mode: 0600
  become: true
  when: app_fightfor_graphql.is_vagrant is not defined or app_fightfor_graphql.is_vagrant == False

- name: Upload public deployment key (Production)
  copy:
    src: "deployment_key.public"
    dest: "/home/{{ app_fightfor_graphql.user }}/.ssh/deployment_key.public"
    owner: "{{ app_fightfor_graphql.user }}"
    mode: 0600
  when: app_fightfor_graphql.is_vagrant is not defined or app_fightfor_graphql.is_vagrant == False

- name: Upload private deployment key (Production)
  copy:
    src: "deployment_key.private"
    dest: "/home/{{ app_fightfor_graphql.user }}/.ssh/deployment_key.private"
    owner: "{{ app_fightfor_graphql.user }}"
    mode: 0600
  when: app_fightfor_graphql.is_vagrant is not defined or app_fightfor_graphql.is_vagrant == False

- name: Checkout the project source code from Git (Production)
  git:
    repo: "ssh://git@sunny.diskstation.me/bearnd/fightfor-graphql.git"
    dest: "{{ app_fightfor_graphql.share_dir }}/src"
    depth: 1
    force: yes
    accept_hostkey: true
    ssh_opts: "-o StrictHostKeyChecking=no  -o Port=30001"
    key_file: "/home/{{ app_fightfor_graphql.user }}/.ssh/deployment_key.private"
  when: app_fightfor_graphql.is_vagrant is not defined or app_fightfor_graphql.is_vagrant == False
  become: true

- name: Create configuration file (Development)
  template:
    src: "config_dev.json.j2"
    dest: "{{ app_fightfor_graphql.config_dir }}/fightfor-graphql.json"
    owner: "{{ app_fightfor_graphql.user }}"
    group: "{{ app_fightfor_graphql.group }}"
    mode: 0600
  become: true
  become_user: "{{ app_fightfor_graphql.user }}"
  when: app_fightfor_graphql.is_vagrant is defined and app_fightfor_graphql.is_vagrant == True

- name: Create configuration file (Production)
  template:
    src: "config_prod.json.j2"
    dest: "{{ app_fightfor_graphql.config_dir }}/fightfor-graphql.json"
    owner: "{{ app_fightfor_graphql.user }}"
    group: "{{ app_fightfor_graphql.group }}"
    mode: 0600
  become: true
  become_user: "{{ app_fightfor_graphql.user }}"
  when: app_fightfor_graphql.is_vagrant is not defined or app_fightfor_graphql.is_vagrant == False

- name: Create Gunicorn configuration file (Production)
  template:
    src: "gunicorn_config.py.j2"
    dest: "{{ app_fightfor_graphql.config_dir }}/gunicorn_config.py"
    owner: "{{ app_fightfor_graphql.user }}"
    group: "{{ app_fightfor_graphql.group }}"
    mode: 0600
  become: true
  become_user: "{{ app_fightfor_graphql.user }}"
  when: app_fightfor_graphql.is_vagrant is not defined or app_fightfor_graphql.is_vagrant == False

- name: Install Python package requirements (Production)
  pip:
    chdir: "{{ app_fightfor_graphql.share_dir }}/src/"
    requirements: requirements.txt
    state: latest
    virtualenv: "{{ app_fightfor_graphql.virtual_env_dir }}"
    virtualenv_python: python2.7
  when: app_fightfor_graphql.is_vagrant is not defined or app_fightfor_graphql.is_vagrant == False
  become: true
  become_user: "{{ app_fightfor_graphql.user }}"

- name: Install Python package requirements (Development)
  pip:
    chdir: "/home/vagrant/fightfor-graphql"
    requirements: requirements_dev.txt
    state: latest
    virtualenv: "{{ app_fightfor_graphql.virtual_env_dir }}"
    virtualenv_python: python2.7
  when: app_fightfor_graphql.is_vagrant is defined and app_fightfor_graphql.is_vagrant == True
  become: true
  become_user: "{{ app_fightfor_graphql.user }}"
